[features]
seeds = false
skip-lint = false
[programs.localnet]
drift_vaults = "HxBBGnmMrjmrdNq3EcEYPa8rERPPThsvzt59BGtk8mZb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "HxBBGnmMrjmrdNq3EcEYPa8rERPPThsvzt59BGtk8mZb"
program = "./deps/drift.so"

[[test.genesis]]
address = "DraWMeQX9LfzQQSYoeBwHAgM5JcqFkgrX7GbTfjzVMVL"
program = "./deps/drift_competitions.so"

[scripts]
test = "yarn anchor-tests"
